# Generated by Django 6.1.1 on 2026-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiagnosisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_type', models.CharField(choices=[('rice', 'Rice (ধান)'), ('jute', 'Jute (পাট)')], default='rice', max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='diagnoses/')),
                ('disease_id', models.CharField(max_length=64)),
                ('disease_name_bn', models.CharField(max_length=128)),
                ('disease_name_en', models.CharField(max_length=128)),
                ('confidence', models.FloatField(default=0.0)),
                ('soil_health_score', models.FloatField(default=0.0)),
                ('nitrogen', models.FloatField(default=0.0)),
                ('phosphorus', models.FloatField(default=0.0)),
                ('potassium', models.FloatField(default=0.0)),
                ('soil_ph', models.FloatField(default=0.0)),
                ('previous_crop', models.CharField(default='boro_rice', max_length=64)),
                ('land_unit', models.CharField(default='bigha', max_length=32)),
                ('land_amount', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diagnosis Record',
                'verbose_name_plural': 'Diagnosis Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
